.\" Manpage for dbus-systemd-signals.
.\" Contact k.meliksetian@tu-braunschweig.de to correct errors or typos.
.TH man 8 "07 Juli 2024" "1.0" "dbus-systemd-signals man page"
.SH NAME
dbus\-systemd\-signals \- Read systemd events, e.g. service starting/stopping
.SH SYNOPSIS
.PP
.B dbus\-systemd\-signals@\&.service
.PP
.B ./dbus\-systemd\-signals\-exec
.PP
.SH DESCRIPTION
.PP
\fIdbus\-systemd\-signals\fR is a utility designed to read systemd events, because it's a cheaper way of monitoring
systemd events than reading systemd logs\&.
It will send the events to 
the POSIX message queue \fI/dbus-systemd-signals\fR.
This message is in 
.B InfluxDB\-Line\-Protocol,
and the message queue is managed by
.BR mq_overview (7)\&. 
.PP
.BR posix\-mq\-to\-mqtt\-bridge (8)  
can then send the messages to a MQTT Broker\&.
.PP
.SH OPTIONS 
.SH "SEE ALSO"
.BR posix\-mq\-to\-mqtt\-bridge (8),
.BR mq_overview (7),
.SH ARGUMENTS
The program must be started with 'sudo'.
.SH BUGS
No known bugs.
.SH AUTHOR
Karen Meliksetian (k.meliksetian@tu\-braunschweig.de)
