#define _XOPEN_SOURCE 700

#include "signal_handling.h"
#include <signal.h>
#include <stdio.h>
#include <unistd.h>

volatile sig_atomic_t keep_running = 1;

/* Only async-safe function `write` is used to print a message */
void print_signal(int signal) {
        char msg1[] = "\nReceived signal ";
        char msg2[] = ", stopping...\n";
        int length = 0;

        /* Write first part of the message */
        write(STDOUT_FILENO, msg1, sizeof(msg1) - 1);

        /* Write signal */
        switch (signal) {
        case SIGINT:
                write(STDOUT_FILENO, "SIGINT", sizeof("SIGINT") - 1);
                break;
        case SIGTERM:
                write(STDIN_FILENO, "SIGTERM", sizeof("SIGTERM") - 1);
                break;
        case SIGHUP:
                write(STDIN_FILENO, "SIGHUP", sizeof("SIGHUP") - 1);
                break;
        case SIGQUIT:
                write(STDIN_FILENO, "SIGQUIT", sizeof("SIGQUIT") - 1);
                break;
        default:
                write(STDIN_FILENO, "UNKNOWN", sizeof("UNKNOWN") - 1);
                break;
        }


        /* Write the final part of the message */
        write(STDOUT_FILENO, msg2, sizeof(msg2) - 1);
}

/* Signal handler */
void handle_signal(int signal) {
        print_signal(signal);
        keep_running = 0;
}

int setup_signal_handling() {
        /* Register signal handler */
        struct sigaction sa;
        sa.sa_handler = handle_signal;
        sa.sa_flags = 0;
        sigemptyset(&sa.sa_mask);

        /* Generated by Ctrl+C in the terminal*/
        if (sigaction(SIGINT, &sa, NULL) == -1) {
                perror("sigaction failed");
                return -1;
        }

        /* Sent by 'kill' command by default */
        if (sigaction(SIGTERM, &sa, NULL) == -1) {
                perror("sigaction failed");
                return -1;
        }

        /* Sent when a controlling terminal is closed or a controlling process terminates */
        if (sigaction(SIGHUP, &sa, NULL) == -1) {
                perror("sigaction failed");
                return -1;
        }

        /* Generated by Ctrl+\ */
        if (sigaction(SIGQUIT, &sa, NULL) == -1) {
                perror("sigaction");
                return -1;
        }
        return 0;
}