default:
  image: gcc:latest
  before_script:
    - apt-get update && apt-get install -y cmake libsensors4-dev
    - git clone https://github.com/eclipse/paho.mqtt.c.git
    - cd paho.mqtt.c
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr/local/paho-mqtt ..
    - make
    - make install
    - cd ../..

stages:
  - build
  - run

build:
    stage: build
    allow_failure: false
    when: always
    script:
      - mkdir -p build && cd build
      - cmake ..
      - make
    artifacts:
      paths:
          - build/
      expire_in: 1 week

run_bridge:
  stage: run
  allow_failure: false
  when: on_success
  dependencies:
    - build
  script:
    - cd build
    - ./bridge-exec

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - build/